version: '2'

services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    depends_on:
      - zoo1
    container_name: kafka
  
  discovery:
    restart: always
    image: discovery:standard
    ports:
      - "7171:7171"    
    volumes:
      - ./volumes/discovery/config:/app/config:Z
    command: /supervisor.sh

  imserver:
    restart: always
    image: imserver:standard
    ports:
      - "3109:3109"
      - "3101:3101"
      - "3102:3102"
      - "3103:3103"
    volumes:
      - ./volumes/imserver/config:/app/config:Z
    command: /supervisor.sh
